### ISSUE TITLE
Attack-based (instead of save based) Spellcasting

### ISSUE THREAD

**Issue by kgrubb** [microluxe20/microluxe20#29]
Based on the conversation in #23, Spellcasting could highly benefit from being action/attack based instead of defense/save based. 

As it currently stands, Spell DC is a static number and monsters roll against the Spell DC to see if they can escape the spell's effects. However, save-based spellcasting is backwards to traditional combat. 

There should be a balanced manner in which spells can be offensive, with the target having a static defense against them (although it may be useful to look at still keeping a dynamic defense based on relevant dc saves, if this is not too confusing or complicated).

**Comment by Web-eWorks** [comment]
How balanced should it be? What's the average odds that a target can block the spell? As characters reach level 10 (to say nothing of 20), they're consistently rolling into the mid 20s or higher.

The way I see it, there's two options.
1. Make blocking a spell a difficult thing to do, allowing only sentient characters to make an active defense (with MIND+Level), and using say 10+MIND Stat as static difficulty for offensive spellcasting.
2. Make blocking much more easy and move all attacks (melee, ranged, magic) to stat bonuses only, granting additional attacks periodically on level up. I'm not particularly a fan of this, as it breaks backwards compat with the current system and severely drops the ability of characters to defeat 20+ AC opponents, as well as requiring a complete rewrite of the entire combat system.
