### ISSUE TITLE
Clarify Magic Attack Bonus Usage

### ISSUE THREAD

**Issue by kgrubb** [microluxe20/microluxe20#30]
Based on the conversation in #23, the "bonus" system is fairly easy to understand for Melee and Missile, but the Magic bonus seems unused at best and confusing at worst. 

Personally, in my games, I have yet to use the Magic Bonus, and the only time it seems to be relevant is when a spellcaster uses their wand/staff in combat (which almost never happens in a non melee fashion). As @Web-eWorks has stated, perhaps this bonus can be incorporated into the current spells to make them scale well as the character progresses.

**Comment by Web-eWorks** [comment]
TBH, this is dependent upon #29, and probably should be assigned to 1.8.0.

**Comment by Web-eWorks** [comment]
Closed via #46.
