### ISSUE TITLE
Derivative Licensing

### ISSUE THREAD

**Issue by Web-eWorks** [microluxe20/microluxe20#39]
Your README mentions procedures for releasing derivative works in the `CONTRIBUTING.md` file, but there's no relevant section in the actual document. What specifically are the terms?

Related to that, I am adapting the M20 rules to work with space/sci-fi settings, and I wanted to get some confirmation on what you're okay with inheriting from the default M20 'Product Identity'.

Can I inherit (I'll add to the list as I come across things):
- 'Terador' as the generic name for the setting / Space-UN?
- The list of Psion powers (with moderate tweaking to fit the setting)?
- The Microluxe20 name (to call the rules Microluxe20 Space)?

Also, if I'm reading the LICENSE right, you are claiming your own name as Product Identity, when it is already covered as a Trademark in section 1.

~Perhaps consider licensing the non-document portions of the project (build files, essentially) under MIT? I don't think the OGL applies well to build tooling code.~ Done!

**Comment by Web-eWorks** [comment]
Have you gotten a chance to take a look at this, @kgrubb?

**Comment by kgrubb** [comment]
Hey sorry, been busy. I meant to write terms and never got around to it. I'll try and make a pr with that info later.

For your inherit questions, all of those are fine. 

I'm super bad with licensing. I'll try and get it cleaned up in a minute. I might just go ISC for everything outside of the markdown and make the markdown OGL. Regardless, I have zero problems with you using the build tooling in a separate project or repo if you want.

**Comment by kgrubb** [comment]
Regarding the product identity, from what I see, the product identity in section 1 seems to be for WOTC. A few other microlite20 projects also have personal Product Identity explicitly set at the bottom of the License. I'm not super sure if that's the right way or not though.

**Comment by kgrubb** [comment]
Does this commit cover most/all of your questions? cb17ee3e51cdd78698c5f4ef96704ea0d16a2aa5

If not, feel free to comment on the commit and I'll try to be more punctual in updating the info.

**Comment by Web-eWorks** [comment]
Now that I've had a chance to read the license in depth (and do some reading about it), your name and the Microluxe20 name are explicitly covered in Product Identity. Section 1 defines Product Identity for _everything_ using the license. That is, Dungeons and Dragons, the M20 logo / name, and the Terador setting are all Product Identity, belonging to their various owners. The copyright statement preamble refers to the license itself, rather than the Product Identity.

If you want derivative projects to be able to inherit the setting / characters / name you have created, you'll need to explicitly define them as Open Game Content under the terms of the OGL, or define a separate license agreement (Creative Commons?).

I'll have a PR ready in a few days with the ISC license addition and whatever you decide on with this, @kgrubb.

**Comment by kgrubb** [comment]
was this resolved in #42? The main thing i'm concerned with for microluxe20 licensing for derivatives is "don't make illegal or super weird/bad stuff and claim its microluxe20-related". The space derivative, for example, is more than cool with me.

**Comment by Web-eWorks** [comment]
Almost resolved. The section on derivatives needs a bit more meat to it (see comments on cc2302a6cf743c8e94c449e230c9a1b9e69b13d5).

Specifically, if you want people to be able to inherit equipment or spell lists, or setting information / names / characters / races / etc. you need to specify that (as it falls under Product Identity otherwise).

For example, the equipment lists _may_ be inherited Open Game Content (if I'm reading the Copyright Notices correctly), but without explicitly specifying that, they get in a quagmire that may fall under Product Identity. It gets even iffier when you consider that they may have been modified by you, me or others working on this product and not the product they were inherited from.

**Comment by kgrubb** [comment]
resolved via https://github.com/microluxe20/microluxe20/pull/44
