### ISSUE TITLE
Host M20 Documents on Microluxe20.com

### ISSUE THREAD

**Issue by Web-eWorks** [microluxe20/microluxe20#41]
Pursuant to our discussion on other issues, I'm making this to track what needs to be done. These can be split into sub-issues at your convenience.

- [x] Extend build process to create combined PDFs for release.
- [ ] Add MD-to-HTML build step for online-hosted version.
- [ ] Extend current site to host the HTML rule-book.
    - [ ] Move to Jekyll (or another static site generator)
    - [ ] Stay with static HTML
- [ ] Add CI job to update the website's copy of the rulebook when new releases are cut.

Also, I wanted to ask – what's the hosting situation for 'officially-licensed' derivative works?

I'm planning on sticking the M20 space rules on a GH-Pages site when I get done; would a CNAME redirect from `microluxe20.com` be possible? Something like `space.microluxe20.com`? Obviously, this would be subject to periodic review regarding the 'officially-licensed' status, etc.

**Comment by kgrubb** [comment]
Adding some followup from the conversation in #38. I think the plan @Web-eWorks has for compiling and uploading via travis is perfect for this. :100: 👌

**Comment by Web-eWorks** [comment]
Closed in favor of more specific issues here and to be created on the M20 website repo.
