### ISSUE TITLE
Weight Mechanics / Drop weight listings from equipment tables.

### ISSUE THREAD

**Issue by Web-eWorks** [microluxe20/microluxe20#43]
Weight isn't a mechanic in the M20 rulebook. I need to refactor the equipment lists as a result of the font size change, and I don't see what the weight listings are actually useful for, aside from fluff.

Can I remove the weight columns, or would you rather me leave it in?

**Comment by Web-eWorks** [comment]
Pinging @kgrubb. This is a fairly blocking issue, as if I'm keeping it I've got to find another way to organize the Adventuring Equipment table.

**Comment by kgrubb** [comment]
I added weight in [v1.7.1](https://github.com/microluxe20/microluxe20/releases/tag/1.7.1) per a request from someone at a local gameshop. Microluxe20 doesn't have any official encumbrance rules, so if its more hassle than it's worth, we can drop the weight info. 🔪

**Comment by Web-eWorks** [comment]
Will do. The whole weight system is great when you have a computer to take care of it, but constantly recalculating your pack's weight kinda contradicts M20's goals.
