### ISSUE TITLE
1.8.0 Misc Tasks

### ISSUE THREAD

**Issue by Web-eWorks** [microluxe20/microluxe20#45]
These are the tasks I want to get done for a 1.8.0 release.

- [x] Set up build tooling for #49 
- [x] Rewrite Spellcasting (#29, #30)
- [x] Overhaul and tweak GM's guide
    - [x] Creature List
    - [x] Trap List
    - [x] Poisons / Diseases
    - [x] Suggestions / guidelines for table conduct and roleplaying
- [x] Overhaul and tweak Equipment Section
    - [x] Drop weights from items.
    - [x] Slim the Adventuring Gear section, condense some items into a catch-all 'Adventurer's Gear' item.
- [x] Restructure the handbook introduction
    - [x] Finish the TODO I accidentally left in.

EDIT: Some of this has been split into the 1.9.x series.

Once these are accomplished, I think the 1.x branch will be done, and work can start (eventually) on the 2.x series. When the 1.x branch goes stable, I want to poke [donjon](http://donjon.bin.sh/) about supporting Microluxe20 as well as Microlite20.

Feel free to make this a project and/or split it into several issues.

(Also, @kgrubb, is there a place I could ping you for answers  / input with less lag than the Issues board? Would the M20 Discord work?)

**Comment by kgrubb** [comment]
The org's team board or discord are the best places to ping me in a more async fashion.

**Comment by Web-eWorks** [comment]
@kgrubb do you have any input on class-specific metamagic? I can certainly come up with some, but we're looking at 4 specific (if not entirely unique) metamagic spells times the four spellcasting classes.

**Comment by kgrubb** [comment]
I don't have any input yet. I'll try and think of a few ideas in the next few days

**Comment by kgrubb** [comment]
I haven't forgotten this, just been busy. nothing yet still.

**Comment by Web-eWorks** [comment]
That's fine, I'm a bit stalled on the GM's guide myself.

The metamagic and other content-specific tasks have been moved to the 1.9 series, as I can't justify putting off the 1.8 release for three months (or more) while you or I write content.

I had a few general ideas, I'll throw them here and see if it helps your creative process.
- An (arcane?) spell-cancelling metamagic. Needs the metamagic roll to be higher than the spell's casting roll to successfully cancel.
- Various flavor metamagics that add (cheaper) bonuses to a spell in a specific domain (e.g. druids can get +50% power/efficiency/whatever on spells that target plants, clerics for undead, etc.)
- Drop the Mass _x_ spells, use metamagic to make a spell have multiple targets. (The Mass _x_ spells need some improvements even if we don't do this.)
