### ISSUE TITLE
Add Traits system

### ISSUE THREAD

**Issue by Web-eWorks** [microluxe20/microluxe20#51]
While I was working on M20 Space, I came up with a system that may work well in base M20. I call it Traits (or Traits and Quirks, but that's a mouthful to refer to).

The gist of the system is that characters gain situational bonuses or maluses to certain rolls, related to the roleplaying aspect of the character. For example, if a character has a deathly fear of snakes and has trained with bullwhips all their life (I have absolutely no idea who I'm referring to), they may take a trait to reflect that, expressed like this:

> Trait: -3 to all Mind rolls in the presence of snakes.
> Trait: +2 to attacks with a Bullwhip

The way I have it set up in M20 Space is that Traits cost 'trait points' to purchase positive traits, and give trait points when taking negative traits. The specific cost is derived by multiplying the numeric value with a factor related to the specific roll:

| Roll | Factor
| :---- | :-------
| Attack | 4
| Stat | 3
| Skill | 2
| Stat+Skill | 1 

Thus, the aforementioned snake trait gives 9 Trait points that could be spent on other traits or possibly converted into skill points (or something). When combined with the Bullwhip trait, 1 skill point is left, which could be spent on Mind+Knowledge rolls involving ancient Hebrew artifacts, for example.

The factor for Attacks is improvised at the last second and subject to change, as M20 Space uses Stat+Skill for attacks rather than Level+Stat.

On level-up, (or at the Gamemaster's discretion) characters can gain, strengthen, weaken, or lose traits via GM fiat or paying the appropriate cost. (Perhaps through Skill point conversion? 1 SP -> 10 TP?)

A good example is that a Gamemaster can award a positive trait to a character for heroic or extraordinary action, or a negative trait as a consequence or side-effect of a bad or dumb action.

@kgrubb Thoughts?

**Comment by enkryptor** [comment]
I believe that would be against the M20 philosophy. The system itself provides a basic framework, leaving all specific situational bonuses up to the GM. This is the thing that gives the M20 the essential versatility. Squeezing this into a strict trait list, like "-3 to all Mind rolls in the presence of snakes", instead of just GM giving -3 penalty because the character has the fear of snakes, contradicts the main point.

**Comment by Web-eWorks** [comment]
I'm not sure I see your point. Are you contesting this on the basis that characters have to pick from a specific list of traits, (e.g. you can only have a fear of snakes or a liking to bats;) that it's relatively static and written down instead of the GM having to keep track of it in their head; or that the process is (admittedly) fairly awkward and stilted?

I've been playtesting these mechanics in a game I'm running, and I can definitely see that they need to be boiled down and simplified before they're ready for inclusion.

However, I'm going to have to disagree with you about the M20 philosophy - the specific goal of M20 is to create a system that is both appropriate for newcomers and well-rounded for hardened roleplayers alike, while keeping the mechanics simple enough to fit in 35 pages or less. I don't see this system (in it's final incarnation) contradicting this goal - in fact, in my playtesting group, it's already massively improving quality-of-life for new players and GMs.

Part of my goal when working on the M20 rules is to bake good roleplaying into the ruleset. Especially for new players with a ruleset that doesn't touch on it, it's difficult to create a character that goes beyond Stabby-McGenericProtagonist. (I should know, my group is entirely comprised of new players.) The specific thrust of this proposed addition is to integrate personality and story into characters, in a way that players can feel in both roleplaying and rollplaying segments.

**Comment by Web-eWorks** [comment]
This issue has been superseded by #58.
